# Generated by Django 3.2.4 on 2021-06-19 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_news_tag_typetag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='typetag',
            name='value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.tag'),
        ),
    ]
